DROP TABLE USERS;

CREATE TABLE USERS (
		USERNAME VARCHAR(50) NOT NULL,
		USER_ROLE VARCHAR(50) NOT NULL,
		PASSWORD VARCHAR(50) NOT NULL,
		ACTIVE BOOLEAN NOT NULL
	);
	
insert into USERS (USERNAME, USER_ROLE, PASSWORD, ACTIVE) values ('admin', 'ADMINISTRATOR', '5f4dcc3b5aa765d61d8327deb882cf99', TRUE);
